service: sls-newrest-api
custom:
  wsgi:
    app: handler.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-east-1
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  helloWord:
    handler: wsgi.handler
    events:
      - http: 'GET /'
  getStatus:
    handler: wsgi.handler
    events:
      - http: 'GET /status'
plugins:
  - serverless-python-requirements
  - serverless-wsgi
